#!/bin/bash
# File:  generate
# Auth:  K. Loux
# Date:  3/13/2010
# Desc:  This script launches the photomosaic creator and
#        sets up the paths and options to create the image.
#        Simply for convenience.

PICDIR="Pics"
BIGPIC="./CarInterior.JPG"
OUTFILE="Car1.jpg"
SUBSIZE=75
TILESIZE=60
SUBSAMPLES=5
REPEAT=50

# For creating thumbnails
#./PhotoMosaic -dir "/home/Kerry/Projects/PhotoMosaic/temp" -big-pic "$BIGPIC" -o "$OUTFILE" -subsize $SUBSIZE -tilesize $TILESIZE -subsamples $SUBSAMPLES -repeat $REPEAT -save-thumbs $PICDIR

# Normal Use
./PhotoMosaic -dir "$PICDIR" -big-pic "$BIGPIC" -o "$OUTFILE" -subsize $SUBSIZE -tilesize $TILESIZE -subsamples $SUBSAMPLES -repeat $REPEAT
